### ISSUE TITLE
Capturing cursor

### ISSUE THREAD

**Issue by mark2185** [thenaterhood/gscreenshot#115]
Would it be too much of a hassle to capture the cursor as well?

Note: I'm speaking from the CLI perspective, I never used the GUI.

For entire screen capture, it doesn't seem like too much of a difference in the program's behaviour, it captures it where it is when the user runs the command.

As for the "selection screenshot", I'm not sure how to solve that. Because currently it screenshots only when the selection is completed, which means the cursor cannot be captured. 
Unless the "selection screenshot" took the entire screenshot first, and then you select a part of that. But that's not backwards compatible.

**Comment by thenaterhood** [comment]
Thanks for the suggestion!

For the full screen as you say it should be easy enough to add the option.

For region selection I'll have to think about how to do it. It might not be too hard to get something working for folks using slop for region selection because in that case the screenshot and region selection are two separate steps already. gscreenshot could ask for the selection first, let the cursor get moved, then take the screenshot on click.

**Comment by mark2185** [comment]
> gscreenshot could ask for the selection first, let the cursor get moved, then take the screenshot on click.

I don't know, I'm not feeling it.

Taking the screenshot with the cursor in-place and then cropping it to a region sounds more like it.

Imagine it from the perspective of a new user - they press a button, select a region, click, the cursor is still able to move for some reason, then they click the second time, and if the cursor was outside the box, they have no idea why did they have to click the second time.

On the other hand, press a button, the screen becomes still, you can move your cursor but it is still visible on the screenshot, and you select a region and click.

What are your thoughts on it?

**Comment by thenaterhood** [comment]
I see where you're coming from, yeah. It's funny, it really is kind of an odd problem.

I was curious so I did a little research as to how other utilities do it. scrot, xfce4-screenshooter, and gnome-screenshot appear to just not support including the cursor if you're selecting a region. Going that way at least for now would give parity with those other tools and would leave room for future improvement. A compromise could be also adding an option for "crop after taking" or even "add pointer after taking" to stamp a cursor onto it after-the-fact. That might also be a more discoverable way to go about it.

One potential problem I can see with taking the shot then cropping at full size, aside from backwards compatibility issues, is with multi-head displays. I don't know offhand if there's a reliable way to freeze the whole span or tile a full screen image across them reliably.

**Comment by mark2185** [comment]
> I was curious so I did a little research as to how other utilities do it. scrot, xfce4-screenshooter, and gnome-screenshot appear to just not support including the cursor if you're selecting a region. 

But that's the only time I actually _want_ to capture the cursor, because I want to _point_ to something.

> Going that way at least for now would give parity with those other tools and would leave room for future improvement. 

Fair enough, _cursor in some cases_ is better than _/9 cursor_.

>A compromise could be also adding an option for "crop after taking" or even "add pointer after taking" to stamp a cursor onto it after-the-fact. That might also be a more discoverable way to go about it.

I vote for the first option, if my vote counts.

> One potential problem I can see with taking the shot then cropping at full size, aside from backwards compatibility issues, is with multi-head displays. I don't know offhand if there's a reliable way to freeze the whole span or tile a full screen image across them reliably.

Selection screenshot would only capture the active display? By the way, how does it work currently? (Since I don't have multi-head display)

**Comment by thenaterhood** [comment]
> But that's the only time I actually want to capture the cursor, because I want to point to something.
Yup, I understand that. I've had the same need.

> I vote for the first option, if my vote counts.
It's more input than I often get! :)

> Selection screenshot would only capture the active display? By the way, how does it work currently? (Since I don't have multi-head display)
Region selection works across multiple displays, so it's possible select a region that includes part of more than one display. Playing around a little bit I find Flameshot freezes the entire display, across all heads - but without the cursor. There is an open issue on Flameshot to capture the cursor which looks to be leaning towards artificially adding a cursor into the image after the screenshot has been taken.

So what might need to happen is gscreenshot may need to query the cursor coordinates when it takes a screenshot, then it could add a cursor in the right location in the screenshot automatically. The downsides are that the cursor it adds might not match the system theme, and it might require using a delay otherwise the cursor won't be in the region.

**Comment by mark2185** [comment]
> I was curious so I did a little research as to how other utilities do it. scrot, xfce4-screenshooter, and gnome-screenshot appear to just not support including the cursor if you're selecting a region. 

But they _do_ include the cursor when you're taking a screenshot of the entire display?
If so, does it include the cursor when taking a screenshot of multiple heads?

If the answer is yes to both - then it obviously _is_ possible to capture the cursor, regardless of the number of displays, which means the `Flameshot` way is not necessary.

**Comment by thenaterhood** [comment]
It depends on the tool. The Xfce utility does, but scrot doesn't (even without multiple displays actually). So it depends on what the utility supports.

**Comment by mark2185** [comment]
@thenaterhood are you sure?

`scrot v1.5` has a `--pointer` flag which captures the pointer.

For some reason it does _not_ capture it in my terminal (terminator), but I suppose that may be a problem on my side. Works as expected in other windows such as browsers, guake and others.

**Comment by thenaterhood** [comment]
Yes, scrot will capture the cursor when doing the full screen but (at least
on my setup) will not capture it with region selection.

Nate Levesque (pronouns: he/him)
www.natelevesque.com

**Comment by mark2185** [comment]
> will not capture it with region selection

Ah, I may have missed that part...

Oh well, then the "take a shot and then crop" seems the most feasible option.

**Comment by thenaterhood** [comment]
Should be working in https://github.com/thenaterhood/gscreenshot/releases/tag/v2.16.0

I notice scrot got an update for capturing the cursor in region selection with a delay too. I'm not using that in this release, but since scrot now has that ability I'll take that into consideration for the next release and might be able to update the recommended setup (again!).
