### ISSUE TITLE
Slop Error

### ISSUE THREAD

**Issue by JackLincoln** [thenaterhood/gscreenshot#50]
On Arch Linux,  installed from AUR (2.6.1-1),  with Slop version 5.3.37-1

I get an error after choosing window or selection.  I don't get any errors without slop installed.

```
Slop encountered an error:
Failed to compile shader `#version 130
attribute vec2 position;
attribute vec2 uv;
varying vec2 uvCoord;
void main()
{
uvCoord = uv;
gl_Position = vec4(position,0,1);
}
`:
0:1(10): error: GLSL 1.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES
```

**Comment by thenaterhood** [comment]
This appears to be an issue with Slop, rather than gscreenshot. This looks like the issue you're having: https://github.com/naelstrof/slop/issues/70

I'll leave this open for now in case something turns up that I can do about this - perhaps just some better error handling would be good and I'll see what I can do about that.

**Comment by thenaterhood** [comment]
Extra error handling added in #51 , version 2.6.3. I'll update the AUR momentarily.

**Comment by naelstrof** [comment]
I've fixed the issue referenced here with this commit: https://github.com/naelstrof/slop/commit/ee76d8e0dc3a63e54072f873c85f1403799dbf13 My bad.
