### ISSUE TITLE
Selection border lags

### ISSUE THREAD

**Issue by AlexWayfer** [thenaterhood/gscreenshot#77]
What's wrong with it?

![screencast_11-04-2017_01_05_53 am](https://user-images.githubusercontent.com/6510020/32397914-1f4005ee-c0fd-11e7-84f7-487d16aadc62.gif)

[Screencast_11-04-2017_01:05:53 AM.zip](https://github.com/thenaterhood/gscreenshot/files/1442605/Screencast_11-04-2017_01.05.53.AM.zip)

**Comment by thenaterhood** [comment]
Scrot and ImageMagick don't handle compositing correctly which leads to this on some systems. If you call them directly from the command line, you'll find the same thing happens. This isn't a gscreenshot bug.

To fix it, consider installing slop (https://github.com/naelstrof/slop - may be in your package manager, and is available in Copr and the AUR), which gscreenshot will automatically use for selections instead. Slop is able to handle compositing correctly so it doesn't have that problem.

**Comment by AlexWayfer** [comment]
Okay! It helps. Thank you and sorry for the misunderstanding.

Maybe `slop` should be required dependency instead of `scrot`?

**Comment by thenaterhood** [comment]
Scrot and slop serve different purposes. Slop is just used for region selection since it doesn't take screenshots. Gscreenshot will work without slop, but in some setups (such as mine and yours!) slop makes life better.

That said, gscreenshot is modular and supports multiple screenshot backends. Adding support for one that plays a little nicer is definitely a possibility. I had hoped that ImageMagick would serve the purpose, but it seems to have the same problem.
